language: android
android:
  components:
    - build-tools-28.0.3
    - android-27
    - extra

    - sys-img-x86-android-23
    - sys-img-x86-google_apis_playstore-26
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
script:
  - ./gradlew assemble # TODO run tests
before_install:
  - yes | sdkmanager "platforms;android-27" # https://github.com/travis-ci/travis-ci/issues/8874
#before_script:
#  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a # TODO update to android-23; there're problems at the moment https://github.com/googlemaps/android-maps-utils/issues/371#issuecomment-429197624
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &